### ISSUE TITLE
ロボットのトルク定数、逆起電力定数の導出方法

### ISSUE THREAD

**Issue by yonz0803** [calm0815/BalboaRobotics#3]
qiitaで返信を頂き、こちらから投稿させていただきます。
自分もBalboa32u4をラグランジュから線形化し、倒立させようとしています。
パラメータを得るにあたって、トルク定数、逆起電力定数はどうやって求められましたか?
知識が浅く申し訳ありません。

**Comment by calm0815** [comment]
私の都合でQiitaからこちらへ来ていただきありがとうございます。
Balboa32u4を扱ってる人が国内でも少ないので、同じ開発者に出会えてうれしい限りです。

自分は研究の合間に”気が向いたとき”にBalboaの開発をしているため、
返事が遅くなることがあるかもしれませんが、今後ともよろしくお願いします。

**Comment by calm0815** [comment]
質問へ回答する前に質問なんですが、

- Balboa32u4の物理モデルをどこまでモデル化できましたか？
- DCモータの電気的/機械的な挙動が考慮されたモデル式は完成していますか？

**Comment by yonz0803** [comment]
すみません、calm0815さんとやり取りするまでに知識がなく回答できませんでした。。

物理モデルについてはmatlabプログラムを貼らせていただきます。
トルク定数、逆起電力定数についてはpololuのホームページに記載されてある
50:1 HPCBモーターのスペック
[https://www.pololu.com/file/0J1487/pololu-micro-metal-gearmotors-rev-4-1.pdf](url)
からトルク値の単位をNmに変換し電流で割った値と6Vを650rpmをV/sに変換した値で除算して求めたトルク定数0.0426、逆起電力定数0.08814としてシミュレーションした結果全く通らず、calm0815さんの値を拝借させていただいた結果、シミュレーションが通りました。

**Comment by yonz0803** [comment]
すみませんV/s のところrad/s でした失礼しました。

ファイルは正しく貼れているでしょうか？
自分の研究としては最終的には現在の値でなく各モーメントとトルク定数、逆起電力定数を何らかの方法でシステム同定を行い実装することを目的としていて
現在は上記の未知パラメータを仮の値としてcalm0815さんの成果を貸していただき(トルク定数、逆起電力定数は自分で求めたかったのですが上手くいかなかった為)モデリングの確認をするためにLQRによるシミュレーション、Arduinoによる倒立をしなければならず
現在はMatlabで求めた結果をArduinoに実装するやり方が分からず苦戦しています。。

落ちこぼれの学部生の卒業研究の為かなり課題のレベルが低いですが、Arduinoのプログラムに関して教えていただけることありましたらよろしくお願いいたします。

**Comment by yonz0803** [comment]
モデリングに関しては以下のものを参考にしています。
[https://www-p.st.nanzan-u.ac.jp/classes/2019/77375-001/robot2019.pdf](url)

**Comment by yonz0803** [comment]
何度もすみません、URLのコマンドの使い方が間違っていましたので自分のメッセージから開かず、お手数ですがurlを検索して閲覧して頂きたいです。

**Comment by calm0815** [comment]
@yonz0803 さん、返信ありがとうございます。
状況がよく伝わりました。やはり最終目標が同じなので一緒に達成したいですね^ ^
（実はまだ倒立できてないんですよ... ^ ^;）

以下、上記に対するコメントです。

> 物理モデルについてはmatlabプログラムを貼らせていただきます

すいません。こちらからは確認ができないので、おそらくプログラムの貼り付けに失敗しているように思います。サイズが大きいからでしょうか。。
もしよろしければ、私のプロフィールに載せているe-mailアドレスに送付していただけますか？
よろしくお願いします。

> calm0815さんの値を拝借させていただいた結果、シミュレーションが通りました。

私は実機に搭載されているものを実験によって調べました。
その実験内容については少し長くなりそうなので時間をください（私も色々調べながらやってますので。。）

> 現在はMatlabで求めた結果をArduinoに実装するやり方が分からず苦戦しています。。

私達が使用しているBalboaというロボットは少々曲者でして、MatlabからBalboa(Arduino Leonald)への書き込みができません。（メーカーに問い合わせたこともありますが、「ぜひトライしてみてくれ！」的な返事がきました。）
よって、フィードバック制御のプログラムをArduino(C++)プログラムで書く必要があります。
[ここ](https://github.com/calm0815/BalboaRobotics/tree/master/Balboa32U4/Arduino/FeedbackController)に開発中のコードがあります。参考になるかわかりませんが、雰囲気は伝わるかと思います。
そのまま研究にプログラムを使って頂いてもかまいませんし、間違っている箇所などあればどんどんissue出しをお願いします。（できればFork→PullRequestしてもらえると感謝です！）

> 落ちこぼれの学部生の卒業研究の為かなり課題のレベルが低いですが、Arduinoのプログラムに関して教えていただけることありましたらよろしくお願いいたします。

あまり自分や研究をを卑下しないでください。研究や自分自身がかわいそうです。。。
誰しも最初は初心者ですので、一緒に進めていきましょう^ ^

> モデリングに関しては以下のものを参考にしています。
https://www-p.st.nanzan-u.ac.jp/classes/2019/77375-001/robot2019.pdf

すいません。セキュリティにひっかかってみれませんでした。。
サイズが小さいのであればここに貼っていただけますか？
（そもそも部外者が閲覧しても良いのでしょうか...？）

**Comment by calm0815** [comment]
あ、ちなみにですが、
このロボットを現代制御で倒立できたら割とすごいと思います。

**Comment by calm0815** [comment]
@yonz0803 さん、なぜissueの内容を消すのでしょうか...？
issueを取り下げたいのであれば下記の「Close and comment」もしくは右サイドの下にある「Delete issue」を押してください。
